INSERT INTO product(id,name,price,description,image,category,quantity) values(1,'아이패드1',800000,'아이패드입니다1','/images/ipad1.jpg','아이패드',1);
INSERT INTO product(id,name,price,description,image,category,quantity) values(2,'아이패드2',800001,'아이패드입니다2','/images/ipad1.jpg','아이패드',2);
INSERT INTO product(id,name,price,description,image,category,quantity) values(3,'아이패드3',800002,'아이패드입니다3','/images/ipad1.jpg','아이패드',4);
INSERT INTO product(id,name,price,description,image,category,quantity) values(4,'아이패드4',800003,'아이패드입니다4','/images/ipad1.jpg','아이패드',3);

INSERT INTO product(id,name,price,description,image,category,quantity) values(5,'헤드셋',600000,'헤드셋입니다','/images/headset.jpg','헤드셋',3);
INSERT INTO product(id,name,price,description,image,category,quantity) values(6,'헤드셋1',600002,'헤드셋입니다1','/images/headset2.jpg','헤드셋',3);
INSERT INTO product(id,name,price,description,image,category,quantity) values(7,'헤드셋2',600003,'헤드셋입니다2','/images/headset3.jpg','헤드셋',3);
INSERT INTO product(id,name,price,description,image,category,quantity) values(8,'헤드셋3',600004,'헤드셋입니다3','/images/headset4.jpg','헤드셋',2);


INSERT INTO product(id,name,price,description,image,category,quantity) values(9,'노트북1',500001,'노트북입니다1','/images/laptop.jpg','노트북',3);
INSERT INTO product(id,name,price,description,image,category,quantity) values(10,'노트북2',500002,'노트북입니다2','/images/laptop.jpg','노트북',4);
INSERT INTO product(id,name,price,description,image,category,quantity) values(11,'노트북3',500003,'노트북입니다3','/images/laptop.jpg','노트북',3);
INSERT INTO product(id,name,price,description,image,category,quantity) values(12,'노트북',500000,'노트북입니다','/images/laptop.jpg','노트북',3);

INSERT INTO product(id,name,price,description,image,category,quantity) values(13,'마우스',50000,'마우스입니다','/images/mouse.jpg','마우스',3);
INSERT INTO product(id,name,price,description,image,category,quantity) values(14,'마우스1',50001,'마우스입니다1','/images/mouse.jpg','마우스',3);
INSERT INTO product(id,name,price,description,image,category,quantity) values(15,'마우스2',50020,'마우스입니다2','/images/mouse.jpg','마우스',3);
INSERT INTO product(id,name,price,description,image,category,quantity) values(16,'마우스3',50003,'마우스입니다3','/images/mouse.jpg','마우스',3);

-- INSERT INTO users(id,email,password) values(2,'wjdwldns44@gmail.com','1234');
-- INSERT INTO users(id,email,password) values(3,'wjdwldns444@gmail.com','12345');
-- INSERT INTO users(id,email,password) values(4,'wjdwldns4444@gmail.com','123456');
--
